gtkwave::addSignalsFromList rvfpgasim.clk
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.ifu.ifu_i0_instr
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.fpadd_done
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.finish_dly_div_fp
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.out_fpadd
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.simple_fp_adder.state
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.out
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.fpdiv_done
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.fpmul_done
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.out_fpdiv
gtkwave::addSignalsFromList rvfpgasim.veerwolf.rvtop.veer.exu.i_div.out_fpmul